# Generated by Django 4.2.7 on 2025-04-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coupon_options_remove_cartorder_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(default='cash_on_delivery', max_length=100),
        ),
    ]
