# Generated by Django 4.2.7 on 2025-04-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='updated_at',
        ),
    ]
