# Generated by Django 4.2.7 on 2025-04-02 23:12

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_coupon_created_at_remove_coupon_updated_at'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Drop existing tables if they exist
            """
            DROP TABLE IF EXISTS core_address;
            """,
            # Reverse SQL - Do nothing
            "SELECT 1;"
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='add', unique=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey('auth.User', null=True, on_delete=models.SET_NULL)),
            ],
            options={
                'verbose_name_plural': 'Address',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
